config/routes.rb
Fatness::Application.routes.draw do
  devise_for :users

  resources :statistics
  root to: 'statistics#index'

end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  has_one :user
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_filter :authenticate_user!
  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statistics }
    end
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/new
  # GET /statistics/new.json
  def new
    @statistic = Statistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/1/edit
  def edit
    @statistic = Statistic.find(params[:id])
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(params[:statistic])

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render json: @statistic, status: :created, location: @statistic }
      else
        format.html { render action: "new" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statistics/1
  # PUT /statistics/1.json
  def update
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      if @statistic.update_attributes(params[:statistic])
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic = Statistic.find(params[:id])
    @statistic.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fatness</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
      Logged in as <%= current_user.email %>.
          <%= link_to "Log out", destroy_user_session_path %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path %> or
                    <%= link_to "log in", new_user_session_path %>
                      <% end %>
                      </div>
<%= yield %>

</body>
</html>

app/views/statistics/_form.html.erb
<%= form_for(@statistic) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :steps %><br />
    <%= f.number_field :steps %>
  </div>
  <div class="field">
    <%= f.label :taken_on %><br />
    <%= f.date_select :taken_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<h1>Listing statistics</h1>

<table>
  <tr>
    <th>Weight</th>
    <th>Steps</th>
    <th>Taken on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statistics.each do |statistic| %>
  <tr>
    <td><%= statistic.weight %></td>
    <td><%= statistic.steps %></td>
    <td><%= statistic.taken_on %></td>
    <td><%= link_to 'Show', statistic %></td>
    <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
    <td><%= link_to 'Destroy', statistic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Weight:</b>
  <%= @statistic.weight %>
</p>

<p>
  <b>Steps:</b>
  <%= @statistic.steps %>
</p>

<p>
  <b>Taken on:</b>
  <%= @statistic.taken_on %>
</p>


<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>